version: "3.3"
services:
  redis:
    image: redis:6.0.9-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    command: redis-server
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    depends_on:
      - redis
      - db
      - sidekiq
      - chrome
    env_file:
      - .env
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    depends_on:
      - redis
      - db
    env_file:
      - .env
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    depends_on:
      - sidekiq
    volumes:
      - /dev/shm:/dev/shm
volumes:
  redis:
  postgres: