# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pools", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Pool. As you add validations to Pool, be sure to
  # adjust the attributes here as well.
  let(:chain) { create(:chain) }
  let(:block) { create(:block, chain: chain) }
  let(:valid_attributes) {
    { block_id: block.id, users_count: 2, signatures_count: 3, amount: 4.5, stage: 5 }
  }

  let(:invalid_attributes) {
    { block_id: "block.id", users_count: 0, signatures_count: 0, amount: 0, stage: 0 }
  }

  describe "GET /index" do
    it "renders a error response" do
      Pool.create! valid_attributes
      get pools_url
      expect(response).to_not be_successful
    end
  end

  describe "GET /show" do
    it "renders a error response" do
      pool = Pool.create! valid_attributes
      get pool_url(pool)
      expect(response).to_not be_successful
    end
  end
end
