default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: secret

development:
  <<: *default
  database: outerspace_blockchain_development

test:
  <<: *default
  database: outerspace_blockchain_test
#
production:
  <<: *default
  database: outerspace_blockchain_production
  username: outerspace_blockchain
  password: <%= ENV["OUTERSPACE_BLOCKCHAIN_DATABASE_PASSWORD"] %>
