default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: outerspace_blockchain_development

test:
  <<: *default
  database: outerspace_blockchain_test
#
production:
  <<: *default
  database: outerspace_blockchain_production
