name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 3.0.3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Bundle Install
      run: bundle install
    - name: apt update
      run: apt update
    - name: Install Docker Requirement
      run: sudo apt install ca-certificates curl gnupg2 lsb-release
    - name: Create Keyrings for Repositories Signatures Requirements
      run: mkdir -p /etc/apt/keyrings
    - name: Docker apt-gpg Requirements
      run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - name: Docker Repository setup
      run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: apt update && install docker-engine docker-ce docker-ce-cli
      run: apt update && apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin --yes
    - name: Run rake compose:install
      run: bundle exec rake compose:install
   
